-- schema_phase5_backend_intelligence.sql
-- Adds support for persisted backend intelligence layer

ALTER TABLE strategies 
ADD COLUMN IF NOT EXISTS backend_intelligence JSONB DEFAULT NULL;

COMMENT ON COLUMN strategies.backend_intelligence IS 'Persisted intelligence results (gtmScore, verdict, confScore, confidenceMatrix, signalWeights, assumptions, methodology, dataQuality, decisionEngine) generated by gtm-intelligence.js';
